### ISSUE TITLE
There should be a send button for mobile users

### ISSUE THREAD

**Issue by jcgter777** [Legend-of-iPhoenix/iChat#10]
Like in some other things

**Comment by Legend-of-iPhoenix** [comment]
Can't you just press enter? If you are thinking of a special button on the keyboard, there are no ways to do that AFAIK.

**Comment by jcgter777** [comment]
No, like a button at the end of the input box that says "Send" like in some chat rooms

**Comment by Legend-of-iPhoenix** [comment]
But there's a return button on your keyboard :P

You could probably do it anyways, by having a button that sends a fake enter key keyboard event
