### ISSUE TITLE
Timestamps don't work correctly.

### ISSUE THREAD

**Issue by proudloyaltier** [Legend-of-iPhoenix/iChat#13]
On my website, it loads the last comments first! HUGE ISSUE @Legend-of-iPhoenix , fix it NOW

**Comment by proudloyaltier** [comment]
Wait, new comments have longer timestamps? I think that might be it?

**Comment by jcgter777** [comment]
"HUGE ISSUE @Legend-\of-\iPhoenix , fix it NOW" Ahem. iPhoenix is NOT your servant. He will, most likely, out of the kindness of his heart, try and help you, but remember, he is not a code fixing robot or code spewing bot.

**Comment by proudloyaltier** [comment]
Sorry for the harshness, I've just not slept last night.  I know iPhoenix is not my servant.  I just find it annoying sometimes when my website's comment script stops loading what people say

**Comment by Legend-of-iPhoenix** [comment]
This is most likely due to your iChat plugins.

**Comment by proudloyaltier** [comment]
That was fixed 27 days ago :P
