### ISSUE TITLE
Localized timestamps

### ISSUE THREAD

**Issue by ticalc-travis** [Legend-of-iPhoenix/iChat#2]
Instead of doing all the date-to-time-string conversion yourself, it's probably better just calling toLocaleTimeString() on the Date object instead, which will automatically honor the user's local time format. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString

**Comment by Legend-of-iPhoenix** [comment]
Awesome. I'll change it when I get time.

**Comment by Legend-of-iPhoenix** [comment]
Added this in #4
