### ISSUE TITLE
Message loading needs to be deferred until after plugins are loaded

### ISSUE THREAD

**Issue by jcgter777** [Legend-of-iPhoenix/iChat#6]

**Comment by Legend-of-iPhoenix** [comment]
Known bug.

I need to delay parsing of messages until everything in iChat.callbacks has been executed.

**Comment by jcgter777** [comment]
Okay thanks

**Comment by Legend-of-iPhoenix** [comment]
I can fix this by executing the Firebase message loading code after iChat has loaded.

I'm putting the `firebase.database().[...]` code in the second `then` block of the `fetch([url]).then([...]).then([...]);` in the main section of code.

**Comment by Legend-of-iPhoenix** [comment]
Fixed!
