### ISSUE TITLE
DOMContentLoaded not executing

### ISSUE THREAD

**Issue by proudloyaltier** [Legend-of-iPhoenix/iChat#9]
# Expected behavior

# Actual behavior
DOMContentLoaded events don't trigger
https://pastebin.com/GpawXFCB

**Comment by Legend-of-iPhoenix** [comment]
@proudloyaltier, are you referring to user-created DOMContentLoaded events, or iChat's specific DOMContentLoaded event.

If one crashes, the others should still execute, IIRC.

**Comment by proudloyaltier** [comment]
The ones in the bottom of the docs sheets and slides js files

**Comment by proudloyaltier** [comment]
I think I fixed it
